name: bicrypto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aligned_dialog: 0.0.6
  aligned_tooltip: 0.0.1
  audio_session: 0.1.16
  auto_size_text: 3.0.0
  badges: 2.0.2
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
  collection: 1.18.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  emoji_flag_converter: 1.1.0
  equatable: 2.0.5
  expandable: 5.0.1
  file_picker: 8.0.3
  fl_chart: 0.68.0
  flip_card: 0.7.0
  flutter_animate: 4.5.0
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
  flutter_cache_manager: 3.3.1
  flutter_card_swiper: 6.0.0
  flutter_html: 3.0.0-beta.2
  flutter_keyboard_visibility: 5.4.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_rating_bar: 4.0.1
  flutter_spinkit: 5.2.0
  flutter_stripe: ^10.2.0
  flutter_svg: 2.0.9
  flutter_xlider: ^3.5.0
  flutterflow_colorpicker: 
    git:
      url: https://github.com/FlutterFlow/flutterflow_colorpicker.git
      ref: v0.0.1+1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  http: 1.2.1
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl: 0.19.0
  json_path: 0.7.2
  just_audio: 0.9.35
  just_audio_platform_interface: 4.2.1
  just_audio_web: 0.4.8
  k_chart: ^0.7.1
  lottie: 2.7.0
  mime: ^1.0.4
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1
  provider: 6.1.2
  qr_bar_code: ^1.2.0
  rive: 0.12.2
  rive_common: 0.2.8
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  sticky_headers: 0.3.0+2
  styled_divider: 1.0.4
  syncfusion_flutter_gauges: ^26.1.42
  timeago: 3.6.1
  timer_count_down: ^2.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  uuid: ^4.0.0
  video_player: 2.8.6
  video_player_android: 2.4.16
  video_player_avfoundation: 2.6.1
  video_player_platform_interface: 6.2.2
  video_player_web: 2.3.1
  web_socket_channel: ^3.0.0
  webview_flutter: 4.7.0
  webview_flutter_android: 3.15.0
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.12.0
  webviewx_plus: 0.5.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#111417'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Mining
      fonts:
        - asset: assets/fonts/mining.ttf
    - family: Play12
      fonts:
        - asset: assets/fonts/play12.ttf
    - family: Iconify1
      fonts:
        - asset: assets/fonts/iconify1.ttf

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

